# Generated by Django 4.2.5 on 2023-09-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(default='1122edde', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
